### ISSUE TITLE
Multiple Included Tags

### ISSUE THREAD

**Issue by ccl0utier** [splunk/appinspect-cli-action#115]
Are multiple tags supported?  If so, could you please add an example to the `README.md`?

I've unsuccessfully tried:

```
- uses: splunk/appinspect-cli-action@v1.3
        with:
          app_path: ${{ needs.bundle-app.outputs.app_name }}.tar.gz
          included_tags: "splunk_appinspect,cloud"
```

And

```
- uses: splunk/appinspect-cli-action@v1.3
        with:
          app_path: ${{ needs.bundle-app.outputs.app_name }}.tar.gz
          included_tags: 
          - "splunk_appinspect"
          - "cloud"
```
